// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dniygebqzdscndbqwvpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuaXlnZWJxemRzY25kYnF3dnBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5MDc4NzUsImV4cCI6MjA1MDQ4Mzg3NX0.xgnrnzvCvQhg8dIwWz0hkZUO1sWfRQeJadBbApCSp6g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);